# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 363)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_one = QtWidgets.QPushButton(self.centralwidget)
        self.button_one.setGeometry(QtCore.QRect(22, 72, 75, 35))
        self.button_one.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_one.setObjectName("button_one")
        self.button_two = QtWidgets.QPushButton(self.centralwidget)
        self.button_two.setGeometry(QtCore.QRect(103, 72, 75, 35))
        self.button_two.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_two.setObjectName("button_two")
        self.button_parenthesis_open = QtWidgets.QPushButton(self.centralwidget)
        self.button_parenthesis_open.setGeometry(QtCore.QRect(265, 72, 75, 35))
        self.button_parenthesis_open.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_parenthesis_open.setObjectName("button_parenthesis_open")
        self.button_three = QtWidgets.QPushButton(self.centralwidget)
        self.button_three.setGeometry(QtCore.QRect(184, 72, 75, 35))
        self.button_three.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_three.setObjectName("button_three")
        self.label_screen = QtWidgets.QLabel(self.centralwidget)
        self.label_screen.setGeometry(QtCore.QRect(22, 10, 316, 41))
        self.label_screen.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.label_screen.setText("")
        self.label_screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_screen.setIndent(0)
        self.label_screen.setObjectName("label_screen")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 316, 41))
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.button_four = QtWidgets.QPushButton(self.centralwidget)
        self.button_four.setGeometry(QtCore.QRect(22, 115, 75, 35))
        self.button_four.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_four.setObjectName("button_four")
        self.button_five = QtWidgets.QPushButton(self.centralwidget)
        self.button_five.setGeometry(QtCore.QRect(103, 115, 75, 35))
        self.button_five.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_five.setObjectName("button_five")
        self.button_six = QtWidgets.QPushButton(self.centralwidget)
        self.button_six.setGeometry(QtCore.QRect(184, 115, 75, 35))
        self.button_six.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_six.setObjectName("button_six")
        self.button_parenthesis_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_parenthesis_close.setGeometry(QtCore.QRect(265, 115, 75, 35))
        self.button_parenthesis_close.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_parenthesis_close.setObjectName("button_parenthesis_close")
        self.button_zero = QtWidgets.QPushButton(self.centralwidget)
        self.button_zero.setGeometry(QtCore.QRect(103, 201, 75, 35))
        self.button_zero.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_zero.setObjectName("button_zero")
        self.button_sum = QtWidgets.QPushButton(self.centralwidget)
        self.button_sum.setGeometry(QtCore.QRect(22, 201, 75, 35))
        self.button_sum.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_sum.setObjectName("button_sum")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(184, 201, 75, 35))
        self.button_clear.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(85, 85, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_clear.setObjectName("button_clear")
        self.button_substract = QtWidgets.QPushButton(self.centralwidget)
        self.button_substract.setGeometry(QtCore.QRect(22, 287, 75, 35))
        self.button_substract.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_substract.setObjectName("button_substract")
        self.button_percentage = QtWidgets.QPushButton(self.centralwidget)
        self.button_percentage.setGeometry(QtCore.QRect(103, 287, 75, 35))
        self.button_percentage.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_percentage.setObjectName("button_percentage")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(189, 287, 151, 35))
        self.button_exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_exit.setObjectName("button_exit")
        self.button_seven = QtWidgets.QPushButton(self.centralwidget)
        self.button_seven.setGeometry(QtCore.QRect(22, 158, 75, 35))
        self.button_seven.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_seven.setObjectName("button_seven")
        self.button_nine = QtWidgets.QPushButton(self.centralwidget)
        self.button_nine.setGeometry(QtCore.QRect(184, 158, 75, 35))
        self.button_nine.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_nine.setObjectName("button_nine")
        self.button_eight = QtWidgets.QPushButton(self.centralwidget)
        self.button_eight.setGeometry(QtCore.QRect(103, 158, 75, 35))
        self.button_eight.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_eight.setObjectName("button_eight")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(265, 158, 75, 35))
        self.button_dot.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_dot.setObjectName("button_dot")
        self.button_multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.button_multiplication.setGeometry(QtCore.QRect(22, 244, 75, 35))
        self.button_multiplication.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_multiplication.setObjectName("button_multiplication")
        self.button_division = QtWidgets.QPushButton(self.centralwidget)
        self.button_division.setGeometry(QtCore.QRect(103, 244, 75, 35))
        self.button_division.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(255, 170, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_division.setObjectName("button_division")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(184, 244, 75, 35))
        self.button_delete.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(85, 85, 255);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_delete.setObjectName("button_delete")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget)
        self.button_equal.setGeometry(QtCore.QRect(265, 201, 75, 78))
        self.button_equal.setStyleSheet("background-color: rgb(170, 85, 127);\n"
"font: 87 14pt \"Arial Black\";")
        self.button_equal.setObjectName("button_equal")
        self.label_2.raise_()
        self.button_one.raise_()
        self.button_two.raise_()
        self.button_parenthesis_open.raise_()
        self.button_three.raise_()
        self.label_screen.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.button_clear.clicked.connect(self.label_screen.clear) # type: ignore
        self.button_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.button_one.setText(_translate("MainWindow", "1"))
        self.button_one.setShortcut(_translate("MainWindow", "1"))
        self.button_two.setText(_translate("MainWindow", "2"))
        self.button_two.setShortcut(_translate("MainWindow", "2"))
        self.button_parenthesis_open.setText(_translate("MainWindow", "("))
        self.button_parenthesis_open.setShortcut(_translate("MainWindow", "("))
        self.button_three.setText(_translate("MainWindow", "3"))
        self.button_three.setShortcut(_translate("MainWindow", "3"))
        self.button_four.setText(_translate("MainWindow", "4"))
        self.button_four.setShortcut(_translate("MainWindow", "4"))
        self.button_five.setText(_translate("MainWindow", "5"))
        self.button_five.setShortcut(_translate("MainWindow", "5"))
        self.button_six.setText(_translate("MainWindow", "6"))
        self.button_six.setShortcut(_translate("MainWindow", "6"))
        self.button_parenthesis_close.setText(_translate("MainWindow", ")"))
        self.button_parenthesis_close.setShortcut(_translate("MainWindow", ")"))
        self.button_zero.setText(_translate("MainWindow", "0"))
        self.button_zero.setShortcut(_translate("MainWindow", "0"))
        self.button_sum.setText(_translate("MainWindow", "+"))
        self.button_sum.setShortcut(_translate("MainWindow", "+"))
        self.button_clear.setText(_translate("MainWindow", "C"))
        self.button_substract.setText(_translate("MainWindow", "-"))
        self.button_substract.setShortcut(_translate("MainWindow", "-"))
        self.button_percentage.setText(_translate("MainWindow", "%"))
        self.button_percentage.setShortcut(_translate("MainWindow", "%"))
        self.button_exit.setText(_translate("MainWindow", "EXIT"))
        self.button_seven.setText(_translate("MainWindow", "7"))
        self.button_seven.setShortcut(_translate("MainWindow", "7"))
        self.button_nine.setText(_translate("MainWindow", "9"))
        self.button_nine.setShortcut(_translate("MainWindow", "9"))
        self.button_eight.setText(_translate("MainWindow", "8"))
        self.button_eight.setShortcut(_translate("MainWindow", "8"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_dot.setShortcut(_translate("MainWindow", "."))
        self.button_multiplication.setText(_translate("MainWindow", "x"))
        self.button_multiplication.setShortcut(_translate("MainWindow", "*"))
        self.button_division.setText(_translate("MainWindow", "/"))
        self.button_division.setShortcut(_translate("MainWindow", "/"))
        self.button_delete.setText(_translate("MainWindow", "AC"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_equal.setShortcut(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
